import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useRouter } from 'next/router'
import { usePosts } from './usePosts'

const Home: NextPage = () => {
  const router = useRouter();
  const { data: posts, isPending } = usePosts();

  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />

          <div>Current page: {router.pathname}</div>

          <div>
            <h1>Posts</h1>
            {isPending && <p>Loading...</p>}
            {posts && posts.map((post: any) => (
              <div key={post.id} className='post-item'>
                <p>this is a post</p>
                <h2>{post.title}</h2>
                <p>{post.body}</p>
              </div>
            ))}
          </div>
        </main>
      </div>
  )
}

export default Home
